---
namespace: mystudent
name: sysadmin
version: 1.0.0
readme: README.md
authors:
  - Ivan Ivanov <ivan@example.com>
description: My custom collection for system administration
license:
  - GPL-3.0-or-later
tags:
  - linux
  - infrastructure
  - automation
  - nginx
  - postgres
dependencies:
  ansible.posix: ">=1.0.0"
  community.general: ">=5.0.0"
repository: https://gitlab.example.com/mystudent/sysadmin-collection
documentation: https://gitlab.example.com/mystudent/sysadmin-collection/docs
homepage: https://gitlab.example.com/mystudent/sysadmin-collection
issues: https://gitlab.example.com/mystudent/sysadmin-collection/issues
