---
- name: Use custom collection
  hosts: web
  become: yes
  collections:
    - mystudent.sysadmin

  vars_files:
    - ../secrets_dev.yml

  roles:
    - role: mystudent.sysadmin.postgres

  tasks:
    - name: Verify deployment
      debug:
        msg: "Collection role deployed on {{ inventory_hostname }}"
      no_log: true
